// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbwxmtkfojefhketvsyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid3htdGtmb2plZmhrZXR2c3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTEyMDEsImV4cCI6MjA2Mzk4NzIwMX0.0ehfx92HMfhIFyZdt4SZlFfuSpo4T7KlIX5jY8iIklM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);